CREATE TABLE permission (

    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        varchar(64) NOT NULL,
    client_id   varchar(36) NOT NULL,

    CONSTRAINT pk_permission PRIMARY KEY (id),
    CONSTRAINT uk_permission UNIQUE (name, client_id),
    CONSTRAINT fk_permission_client FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE CASCADE

);